/// Use or operation of this code is subject to acceptance of the license available in the code repository for this code.
/// 
Class demo.coffeemakerRequest Extends Ens.Request
{

Property ID As %Numeric;

Storage Default
{
<Data name="coffeemakerRequestDefaultData">
<Subscript>"coffeemakerRequest"</Subscript>
<Value name="1">
<Value>ID</Value>
</Value>
</Data>
<DefaultData>coffeemakerRequestDefaultData</DefaultData>
<Type>%Library.CacheStorage</Type>
}

}
